import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="background-overlay" />
        <main className="main">
          <Navigation />
          {children}
          <footer className="footer">Arc Traders is an independent project and is not affiliated with or endorsed by Embark Studios or Arc Raiders. We do not promote RWT, please report the user if you see any suspicious activity.</footer>
        </main>
      </body>
    </html>
  );
}
